### ISSUE TITLE
Enhancement Request - apply new SR when cloning a service without data

### ISSUE THREAD

**Issue by ChrisBuscaglia** [chris-fox/scripts-tools#10]
@chris-fox Replicating the functionality of schema-only layer packages, but way better.

**Comment by chris-fox** [comment]
@ChrisBuscaglia, so we could do this with a tool parameter, or the other option is to use the environment variables of the tool. When I demo'd the tools the team preferred to keep the extent parameter off the tool to keep the tool simple, so I dropped that and just use the org's default extent. If we went with the environment variable option we could keep the params simple, but still give users the ability to set spatial ref and/or extent.

@ScottOppmann

![image](https://cloud.githubusercontent.com/assets/6796763/18068511/a291a822-6e0f-11e6-9261-b890e2e239c4.png)

**Comment by ScottOppmann** [comment]
I like the idea of putting stuff like this in the Environments section of the tool.  Keeps main tool very simple.

**Comment by chris-fox** [comment]
I pushed a change to the tools so now they will use the output coordinate system environment variable to set the spatial reference of any cloned feature services. If not specified it will default to web mercator auxiliary sphere. In addition the extent environment variable can be used to set the default extent of items.

**Comment by ChrisBuscaglia** [comment]
@chris-fox Nice.  When are the tools planned on being released/supported?

**Comment by chris-fox** [comment]
@ChrisBuscaglia, We are kind of tied to the release of the arcgis python api, which currently is planned to be released with 10.5.

**Comment by chris-fox** [comment]
Output coordinate system environment variable of the tool is observed.
