### ISSUE TITLE
Clone Item fails to clone a webmap

### ISSUE THREAD

**Issue by MikeMillerGIS** [chris-fox/scripts-tools#11]
Enter a webmap ID.  If webmaps are not supported and only FS, can we change the name of the tool?
![image](https://cloud.githubusercontent.com/assets/2707285/18214046/0ba5e466-7119-11e6-8a3c-6f095b41e88b.png)

**Comment by MikeMillerGIS** [comment]
@chris-fox

**Comment by chris-fox** [comment]
@MikeMillerGIS, it should work with web maps, what is the item id of the web map that causes that error?

**Comment by MikeMillerGIS** [comment]
135df7e4a3c040ca8cb7deda99759c37

**Comment by MikeMillerGIS** [comment]
I am signed into DevExt, not production too

**Comment by chris-fox** [comment]
@MikeMillerGIS, I can reproduce in production as well. It is failing cloning the feature service seems to not like the name of the service starting with a number. For example try this:
1. In my content in DevExt select Create > Feature Layer
2. From URL and pass in the url to the service -> http://services2.arcgis.com/PWJUSsdoJDp7SgLj/arcgis/rest/services/08_02_2016__Info_Lookup_Link/FeatureServer
3. Use the same name as the title of the service ie "08_02_2016__Info_Lookup_Link" and click OK to create the service
4. It will return the same error in the website that my tool is returning (my tool is doing the same thing as this workflow through the UI)

If you change the title of the service to begin with a letter or underscore everything will be fine.  So I am thinking my code should just look if the original service name starts with a number and if so add an underscore before it.

**Comment by chris-fox** [comment]
Resolved by testing if service begins with a number and is so add an underscore before it.
