### ISSUE TITLE
Symbology is not maintained in the cloned hosted feature service

### ISSUE THREAD

**Issue by elinz** [chris-fox/scripts-tools#8]
Published a hosted feature service to 10.4.1 portal. The point symbology when the service was published was green squares. Ran the example.py script which calls the deploy_solutions.clone_item to clone the service in a target 10.4.1 portal. The symbology in the cloned item was not maintained; it's now a gray circle.

**Comment by chris-fox** [comment]
@elinz Could you share the service or download it as a fgdb and share it with me? I have tested portal to portal with a feature service with simple and unique value renderes and they both worked for me.

**Comment by chris-fox** [comment]
Discovered the symbology was being maintained properly. Sometimes when you add a feature service to a new map it prompts you to change the symbology which is why it looked like it wasn't being maintained.
