### ISSUE TITLE
Spatial reference/Extent information is incorrect after cloning hosted feature service

### ISSUE THREAD

**Issue by elinz** [chris-fox/scripts-tools#9]
Published a hosted feature service to 10.4.1 portal.  The spatial reference info displayed on the ArcGIS Server FeatureServer endpoint is shown below:
![image](https://cloud.githubusercontent.com/assets/4635490/17949714/99f4580c-6a0b-11e6-96ed-b110b84fe797.png)

After cloning the service to another 10.4.1 portal the spatial reference info is missing the EPSG number for the spatial reference and the extent values are not correct:
![image](https://cloud.githubusercontent.com/assets/4635490/17949787/e548e00c-6a0b-11e6-8e03-64038fa54e3c.png)

**Comment by chris-fox** [comment]
I fixed a bug with how spatial reference was being set in 5f3cbd6. This fixed it for Portal 10.4.1. ArcGIS Online still drops it from the resulting spatial reference, so not sure if Portal 10.5 will too.

In regards to extent, this is behaving as designed. Currently if you don't pass anything into the extent parameter of clone_item, it will use the default extent defined in the organization. This was the requested behavior by the team.

**Comment by chris-fox** [comment]
Both Extent and Output Coordinate system environment variables are observed by the tool. If not specified, the extent will default to the extent defined in the org and the spatial reference will default to web mercator.
